version: '3.3' 

services:
  my-frontend:
    build:
      context: ./frontend
    container_name: vite
    depends_on:
      - my-java
    ports:
      - "3456:80"

  my-java:
    build: 
      context: ./backend
    container_name: my-java
    depends_on:
      - postgres  
    env_file:
      - ./.env
    environment:
      - SQL_SERVER=postgres
      - APP_DATABASE=${APP_DATABASE}
      - LOG_FOLDER=${LOG_FOLDER}
      - SECRET_KEY=${SECRET_KEY}
      - SQL_PORT=${SQL_PORT}
      - APP_USER_NAME=${APP_USER_NAME}
      - APP_PASSWORD=${APP_PASSWORD}
  
  postgres:
    build:
      context: ./db
    container_name: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${APP_DATABASE}
      POSTGRES_USER: ${APP_USER_NAME}
      POSTGRES_PASSWORD: ${APP_PASSWORD}
