pipeline {
    agent {
        docker {
            image 'maven@sha256:7106ce47b5c226ee21bac386cb706ff9f3db7ac2f15e251e3aa491fcbfc30028'
            args '-u root --privileged --net="jenkins" -v $HOME/.m2:/root/.m2'
        }
    }
    environment {
    REPOSITORY = 'iphun/'
    DOCKERHUB_CREDENTIALS=credentials('dockerHub')
    IMAGE_NAME = 'bytebattlers-backend'
  }
    stages {
        stage('validate') {
            steps {
                catchError {
                        sh 'mvn clean validate -B -f ./backend/pom.xml'
                }
            }
        }
        stage('Compile') {
            steps {
                catchError {
                        sh 'mvn compile -B -f ./backend/pom.xml'
                }
            }
        }
        stage('Test') {
            steps {
                catchError {
                        sh 'mvn test -B -f ./backend/pom.xml'
                }
            }
        }
        stage('Package') {
            steps {
                catchError {
                        sh 'mvn package -B -f ./backend/pom.xml'
                }
            }
        }
        stage('Verify') {
            steps {
                catchError {
                        sh 'mvn verify -B -f ./backend/pom.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonarqube') {
                      sh 'mvn clean verify -f ./backend/pom.xml sonar:sonar -Dsonar.projectKey=Bytebattlers-backend -Dsonar.projectBaseDir=./backend'
                }
            }
        }

        stage('Building image') {
            steps{
                script {
                        sh 'docker build -f ./backend/Dockerfile -t ${REPOSITORY}${IMAGE_NAME}:latest -t ${REPOSITORY}${IMAGE_NAME}:${BUILD_NUMBER} ./backend' }
            }
        }

        stage('Docker Login and Push') {
                steps {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    sh 'docker push ${REPOSITORY}${IMAGE_NAME}:${BUILD_NUMBER}'
                    sh 'docker push ${REPOSITORY}${IMAGE_NAME}:latest'
                }
        }

        stage('Extended notification') {
            steps {
                emailext (
                    subject: '$DEFAULT_SUBJECT',
                    body: '$DEFAULT_CONTENT',
                    to: '$DEFAULT_RECIPIENTS',
                    recipientProviders: [ requestor() ]
                )
            }
        }
    }
    
}
